[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg>=1.4",
    "mutagen>=1.47.0",
    "pillow>=11.2.1",
    "pydub>=0.25.1",
    "streamlit>=1.45.1",
]
